n_train_jets: 2
n_test_jets: -1
valid_fraction: 0.2
max_constits: 80
tagger_type: efn
num_epochs: 1
batch_size: 64
data_path: /Users/lucascurtin/Desktop/CERN_DATA"
figure_path: /Users/lucascurtin/Desktop/TopTagGNN/figures