[tool.ruff] 
line-length = 100
ignore = ["D203"]
show-source = true

[tool.black] 
line-length = 100 
target-version = ['py3.8.2'] 

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 20